version: '3.4'

services:
  FoodRescue.api:
    image: ${DOCKER_REGISTRY-}foodrescueapi
    build:
      context: .
      dockerfile: FoodRescue.API/Dockerfile

  foodrescuedb:
    image: mcr.microsoft.com/mssql/server:2017-latest

