version: '3.4'

services:

  foodrescuedb:
    container_name: foodrescuedb
    environment:
        SA_PASSWORD: "Admin1234"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1433:1433"

  FoodRescue.api:
    container_name: FoodRescue.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=foodrescuedb;Database=FoodRescueDb;User Id=sa;Password=Admin1234;TrustServerCertificate=True"
      - "TokenConfiguration:Secret=yoursecret12345123120319230345345435"
    depends_on:
      - foodrescuedb
    ports:
      - "8001:80"